version: '3.9'
services:
    ####### APP #########
    meu-app:
      image: racascao/laravel:1.1
      volumes:
        - '../:/var/www/app'
      tty: true
      ports:
        - 8077:8080
    ####### POSTGRESS #########
    meu-app-postgress:
      image: postgres:14
      ports:
        - 5418:5432
      environment:
        - POSTGRESS_DB=treinamento
        - POSTGRESS_USER=treinamento
        - POSTGRESS_PASSWORD=treinamento
      volumes:
        - postgress-treinamento-volume:/var/lib/postgresql/data
   
volumes:
  postgress-treinamento-volume: